version: "3.9"
services:
  prometheus:
    image: bitnami/prometheus:2.54.0
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      - SERVER_IP=${SERVER_IP}
    command:
      - "--enable-feature=promql-experimental-functions"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    networks:
      - db

  grafana:
    image: bitnami/grafana:11.5.2
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/opt/bitnami/grafana/provisioning
    volumes:
      - ./grafana/data:/opt/bitnami/grafana/data
      - ./grafana/config/grafana.ini:/opt/bitnami/grafana/conf/grafana.ini
      - ./grafana/dashboards:/opt/bitnami/grafana/dashboards
      - ./grafana/provisioning:/opt/bitnami/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - db

networks:
  db:
    driver: bridge