apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    uid: prometheusdatasource
    jsonData:
      httpMethod: POST
    editable: true

  - name: ClickHouse
    type: grafana-clickhouse-datasource
    jsonData:
      defaultDatabase: default
      port: 9000
      host: $CLICKHOUSE_HOST
      username: $CLICKHOUSE_USERNAME
      tlsSkipVerify: false
    secureJsonData:
      password: $CLICKHOUSE_PASSWORD
