{
 "title": "Аналитика файлов",
 "tags": [
  "prometheus",
  "grafana",
  "python"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Время обработки файлов",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "file_processing_time_seconds_sum unless (time() - file_upload_time > $__range)\n",
     "legendFormat": " {{script_name}} - {{file_name}}"
    }
   ]
  },
  {
   "title": "Время, которое прошло после загрузки файлов",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(time() - file_upload_time < $__range)",
     "legendFormat": " {{script_name}} - {{file_name}}"
    }
   ]
  },
  {
   "title": "Кол-во загрузок по файлам",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(files_processed_total unless (time() - file_upload_time > $__range))\n",
     "legendFormat": "{{script_name}} - {{file_name}}"
    }
   ]
  },
  {
   "title": "Кол-во строк в файлах",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rows_in_json_total unless (time() - file_upload_time > $__range)\n",
     "legendFormat": "{{script_name}} - {{file_name}}"
    }
   ]
  },
  {
   "title": "Отслеживание обработки в реальном времени",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "active_file_processing unless (time() - file_upload_time > $__range)\n",
     "legendFormat": "{{script_name}} - {{file_name}}"
    }
   ]
  },
  {
   "title": "Отслеживание обработки в реальном времени",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "increase(active_file_processing[1m])",
     "legendFormat": "{{script_name}} - {{file_name}}"
    }
   ]
  }
 ]
}