{
 "title": "All Enriched Line Report",
 "tags": [
  "clickhouse",
  "db",
  "all_enriched_line_report"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Схема",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT current_database, count(query_id) as cnt FROM \"system\".\"query_log\" WHERE ( query_duration_ms > 3000 ) AND ( http_user_agent = 'DataLens' ) AND ( type = 'QueryFinish' ) GROUP BY current_database ORDER BY cnt DESC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Таблица",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT table_name, count(query_id) AS cnt \r\nFROM (SELECT query_id, arrayJoin(tables) AS table_name \r\nFROM system.query_log \r\nWHERE query_duration_ms > 10000 \r\nAND http_user_agent = 'DataLens' \r\nAND type = 'QueryFinish' \r\nAND current_database = 'default' \r\nAND event_date > now() - INTERVAL 7 DAY) \r\nGROUP BY table_name \r\nORDER BY cnt DESC \r\nLIMIT 1000;"
    }
   ]
  },
  {
   "title": "Столбцы",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    substring(column_name, position(column_name, '.') + 1) AS clean_column_name,\r\n    count(query_id) AS cnt\r\nFROM\r\n(\r\n    SELECT\r\n        query_id,\r\n        arrayJoin(columns) AS column_string,\r\n        arrayJoin(extractAll(column_string, '\\\\b\\\\w+\\\\.\\\\w+\\\\b.\\\\w+\\\\b')) AS column_name\r\n    FROM system.query_log\r\n    WHERE\r\n        type = 'QueryFinish'\r\n        AND query_duration_ms > 10000\r\n        AND http_user_agent = 'DataLens'\r\n        AND current_database = 'default'\r\n        AND event_date > now() - INTERVAL 7 DAY\r\n)\r\nGROUP BY clean_column_name\r\nORDER BY cnt DESC\r\nLIMIT 1000;"
    }
   ]
  },
  {
   "title": "Длительные запросы",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT query_id, query_duration_ms/1000 as seconds \r\nFROM \"system\".\"query_log\"\r\nWHERE ( query_duration_ms > 3000 ) \r\nAND ( http_user_agent LIKE '%DataLens%' ) \r\nAND ( databases = ['default'] ) \r\nAND ( type = 'QueryFinish' ) \r\nAND ( type = 'QueryFinish' )\r\nAND (event_date > now() - INTERVAL 7 DAY)\r\n ORDER BY query_duration_ms DESC LIMIT 100"
    }
   ]
  },
  {
   "title": "Используемая память",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT query_id, memory_usage/1000000 as megabytes \r\nFROM \"system\".\"query_log\" \r\nWHERE ( http_user_agent = 'DataLens' ) \r\nAND ( type = 'QueryFinish' ) \r\nAND ( query_duration_ms > 35000 )\r\nAND (event_date > now() - INTERVAL 7 DAY)\r\nORDER BY memory_usage DESC LIMIT 100"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT query, MAX(memory_usage)/1000000 as \"usage memory , megabytes\"\r\nFROM system.query_log\r\nWHERE ( http_user_agent = 'DataLens' ) \r\nAND ( type = 'QueryFinish' ) AND current_database = 'default'\r\nGROUP BY query\r\nORDER BY MAX(memory_usage) DESC LIMIT 10"
    }
   ]
  }
 ]
}