{
 "title": "ClickHouse",
 "description": "ClickHouse internal exporter metrics",
 "tags": [
  "clickhouse",
  "db",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Node",
    "query": {
     "query": "label_values(ClickHouseAsyncMetrics_Uptime, instance)"
    }
   },
   { "name": "trends", "label": "Show trends", "query": "Yes : 1, No : null" },
   { "name": "peaks", "label": "Show peaks", "query": "Yes : 1, No : null" }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_VersionInteger"
    },
    { "expr": "ClickHouseMetrics_Revision" },
    {
     "expr": "ClickHouseAsyncMetrics_NumberOfTables"
    },
    { "expr": "ClickHouseAsyncMetrics_Uptime" },
    {
     "expr": "ClickHouseAsyncMetrics_NumberOfDatabases"
    }
   ]
  },
  {
   "title": "Используемая Память",
   "type": "timeseries",
   "description": "Показывает текущее использование памяти системой ClickHouse.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Колличество подключений",
   "type": "timeseries",
   "description": "Отображает текущее количество активных HTTP подключений к серверу ClickHouse.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_HTTPConnection",
     "legendFormat": "http - {{instance}}"
    }
   ]
  },
  {
   "title": "Задержка при чтении",
   "type": "timeseries",
   "description": "Отображает количество случаев задержки при чтении данных из ClickHouse.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBackoff{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_ReadBackoff{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Медленные чтения",
   "type": "timeseries",
   "description": "Показывает количество медленных операций чтения данных в ClickHouse.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SlowRead{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_SlowRead{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Запросы",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Запросы",
   "type": "timeseries",
   "description": "Показывает общее количество запросов, обрабатываемых ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_Query{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_Query{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Запросы SELECT",
   "type": "timeseries",
   "description": "Показывает количество запросов типа SELECT, обрабатываемых ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectQuery{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_SelectQuery{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Запросы INSERT",
   "type": "timeseries",
   "description": "Показывает количество запросов типа INSERT, обрабатываемых ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_InsertQuery{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_InsertQuery{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Неудачные запросы SELECT",
   "type": "timeseries",
   "description": "Показывает количество неудачных запросов типа SELECT в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_FailedSelectQuery{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_FailedSelectQuery{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Неудачные запросы",
   "type": "timeseries",
   "description": "Показывает количество всех неудачных запросов в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_FailedQuery{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_FailedQuery{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Превышение лимита памяти для запросов",
   "type": "timeseries",
   "description": "Показывает количество случаев превышения лимита памяти для запросов в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_QueryMemoryLimitExceeded{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_QueryMemoryLimitExceeded{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Прерывание запросов",
   "type": "timeseries",
   "description": "Показывает количество прерванных запросов в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseMetrics_QueryPreempted{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseMetrics_QueryPreempted{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Неудачные запросы INSERT",
   "type": "timeseries",
   "description": "Показывает количество неудачных запросов типа INSERT в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_FailedInsertQuery{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_FailedInsertQuery{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Среднее время выполнения запросов",
   "type": "timeseries",
   "description": "Показывает среднее время выполнения запросов в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_QueryTimeMicroseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_Query{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Среднее время выполнения запросов SELECT",
   "type": "timeseries",
   "description": "Показывает среднее время выполнения запросов типа SELECT в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_SelectQueryTimeMicroseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_SelectQuery{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Среднее время выполнения запросов INSERT",
   "type": "timeseries",
   "description": "Показывает среднее время выполнения запросов типа INSERT в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_InsertQueryTimeMicroseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_InsertQuery{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Вставка",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Вставленные строки",
   "type": "timeseries",
   "description": "Показывает количество вставленных строк в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_InsertedRows{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_InsertedRows{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Вставленные байты",
   "type": "timeseries",
   "description": "Показывает количество вставленных байтов данных в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_InsertedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_InsertedBytes{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Задержанные вставки",
   "type": "timeseries",
   "description": "Показывает количество задержанных операций вставки данных в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_DelayedInserts{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_DelayedInserts{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Отклоненные вставки",
   "type": "timeseries",
   "description": "Показывает количество отклоненных операций вставки данных в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_RejectedInserts{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_RejectedInserts{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Среднее время задержки вставок блоков",
   "type": "timeseries",
   "description": "Показывает среднее время задержки вставок блоков данных в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "increase(ClickHouseProfileEvents_DelayedInsertsMilliseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_DelayedInserts{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Выборка",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Часть данных",
   "type": "timeseries",
   "description": "Показывает количество частей данных, выбраных из ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedParts{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_SelectedParts{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Диапазоны",
   "type": "timeseries",
   "description": "Показывает количество выбранных диапазонов данных в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedRanges{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_SelectedRanges{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Метки",
   "type": "timeseries",
   "description": "Показывает количество выбранных меток данных в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedMarks{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_SelectedMarks{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Строки",
   "type": "timeseries",
   "description": "Показывает количество выбранных строк данных в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedRows{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_SelectedRows{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Байты",
   "type": "timeseries",
   "description": "Показывает количество выбранных байтов данных в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "max_over_time( (irate(ClickHouseProfileEvents_SelectedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
     "legendFormat": "peaks - {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_SelectedBytes{instance=~\"$instance\"}[$__rate_interval]) * $trends",
     "legendFormat": "trend - {{instance}}"
    }
   ]
  },
  {
   "title": "Ввод Вывод",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Операции lseek",
     "type": "timeseries",
     "description": "Показывает количество операций lseek, выполняемых в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_Seek{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_Seek{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Открытые файлы",
     "type": "timeseries",
     "description": "Показывает количество операций открытия файлов в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_FileOpen{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_FileOpen{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Чтение из файлового дескриптора",
     "type": "timeseries",
     "description": "Показывает количество операций чтения из файловых дескрипторов в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorRead{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorRead{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Запись в файловый дескриптор",
     "type": "timeseries",
     "description": "Показывает количество операций записи в файловые дескрипторы в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWrite{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWrite{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Неудачные операции чтения из файлового дескриптора",
     "type": "timeseries",
     "description": "Показывает количество неудачных операций чтения из файловых дескрипторов в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadFailed{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadFailed{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Прочитанные байты из файлового дескриптора",
     "type": "timeseries",
     "description": "Показывает скорость чтения байтов из файлового дескриптора.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadBytes{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Прочитанные сжатые байты",
     "type": "timeseries",
     "description": "Показывает скорость чтения сжатых данных.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReadCompressedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReadCompressedBytes{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Сжатые блоки",
     "type": "timeseries",
     "description": "Показывает количество сжатых блоков данных, прочитанных в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_CompressedReadBufferBlocks{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_CompressedReadBufferBlocks{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Реплика",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Реплика только для чтения",
     "type": "timeseries",
     "description": "Отображает статус реплик, доступных только для чтения в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ClickHouseMetrics_ReadonlyReplica",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Неудачные операции получения реплицированных частей",
     "type": "timeseries",
     "description": "Показывает количество неудачных операций получения реплицированных частей данных в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartFailedFetches{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReplicatedPartFailedFetches{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Операции получения реплицированных частей",
     "type": "timeseries",
     "description": "Показывает количество успешных операций получения реплицированных частей данных в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartFetches{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReplicatedPartFetches{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Операции получения или слияния реплицированных частей",
     "type": "timeseries",
     "description": "Показывает количество операций получения или слияния реплицированных частей данных в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartFetchesOfMerged{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReplicatedPartFetchesOfMerged{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Слияние реплицированных частей",
     "type": "timeseries",
     "description": "Показывает количество операций слияния реплицированных частей данных в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_ReplicatedPartMerges{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_ReplicatedPartMerges{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Слияние",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Слияние данных",
     "type": "timeseries",
     "description": "Показывает количество операций слияния данных в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_Merge{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_Merge{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Слитые строки",
     "type": "timeseries",
     "description": "Показывает количество строк, слитых в ходе операций слияния данных в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergedRows{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MergedRows{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Несжатые байты при слиянии",
     "type": "timeseries",
     "description": "Показывает количество несжатых байтов данных, полученных в ходе операций слияния данных в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergedUncompressedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MergedUncompressedBytes{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Средняя длительность слияния",
     "type": "timeseries",
     "description": "Показывает среднюю продолжительность операций слияния данных в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "increase(ClickHouseProfileEvents_MergesTimeMilliseconds{instance=~\"$instance\"}[$__rate_interval]) / increase(ClickHouseProfileEvents_Merge{instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Строки в MergeTree",
     "type": "timeseries",
     "description": "Показывает количество строк данных, записанных в MergeTree в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterRows{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MergeTreeDataWriterRows{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Блоки в MergeTree",
     "type": "timeseries",
     "description": "Показывает количество блоков данных, записанных в MergeTree в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterBlocks{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MergeTreeDataWriterBlocks{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Несжатые байты в MergeTree",
     "type": "timeseries",
     "description": "Показывает количество несжатых байтов данных, записанных в MergeTree в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterUncompressedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MergeTreeDataWriterUncompressedBytes{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Сжатые байты в MergeTree",
     "type": "timeseries",
     "description": "Показывает количество сжатых байтов данных, записанных в MergeTree в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MergeTreeDataWriterCompressedBytes{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MergeTreeDataWriterCompressedBytes{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Зарезервированное место на диске",
     "type": "timeseries",
     "description": "Показывает объем зарезервированного на диске пространства для операций слияния данных в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ClickHouseMetrics_DiskSpaceReservedForMerge",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Кэш",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Попадания в кэш несжатых данных",
     "type": "timeseries",
     "description": "Показывает количество успешных попаданий в кэш несжатых данных в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_UncompressedCacheHits{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_UncompressedCacheHits{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Промахи в кэше несжатых данных",
     "type": "timeseries",
     "description": "Показывает количество промахов в кэше несжатых данных в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_UncompressedCacheMisses{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_UncompressedCacheMisses{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Попадания в кэш меток",
     "type": "timeseries",
     "description": "Показывает количество успешных попаданий в кэш меток в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MarkCacheHits{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MarkCacheHits{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    },
    {
     "title": "Промахи в кэше меток",
     "type": "timeseries",
     "description": "Показывает количество промахов в кэше меток в ClickHouse.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "max_over_time( (irate(ClickHouseProfileEvents_MarkCacheMisses{instance=~\"$instance\"}[2m]))[$__rate_interval:15s] ) * $peaks",
       "legendFormat": "peaks - {{instance}}"
      },
      {
       "expr": "rate(ClickHouseProfileEvents_MarkCacheMisses{instance=~\"$instance\"}[$__rate_interval]) * $trends",
       "legendFormat": "trend - {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Части",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Временные части данных",
   "type": "timeseries",
   "description": "Показывает количество временных частей данных в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_PartsTemporary",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Предварительно зафиксированные части данных",
   "type": "timeseries",
   "description": "Показывает количество предварительно зафиксированных частей данных в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_PartsPreCommitted",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Зафиксированные части данных",
   "type": "timeseries",
   "description": "Показывает количество окончательно зафиксированных частей данных в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_PartsCommitted",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Удаление при уничтожении",
   "type": "timeseries",
   "description": "Part was moved to another disk and should be deleted in own destructor.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_PartsDeleteOnDestroy",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Удаляемые части данных",
   "type": "timeseries",
   "description": "Показывает количество частей данных, помеченных для удаления в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_PartsDeleting",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Компактные части данных",
   "type": "timeseries",
   "description": "Показывает количество компактных частей данных в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ClickHouseMetrics_PartsCompact", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Широкие части данных",
   "type": "timeseries",
   "description": "Показывает количество широких частей данных в ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ClickHouseMetrics_PartsWide", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Часть данных в памяти",
   "type": "timeseries",
   "description": "Показывает количество частей данных, находящихся в оперативной памяти ClickHouse.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_PartsInMemory",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}