{
 "title": "DC Table Sync Updates",
 "description": "Время указано во временной зоне сервера (для получения Московского времени нужно отнять 3 часа)",
 "tags": [
  "clickhouse",
  "db",
  "DC"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Таблица terminals_capacity последние обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'terminals_capacity'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "terminals_capacity дата и время последнего обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'terminals_capacity' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица completed_repackages_report последние обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'completed_repackages_report'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "completed_repackages_report дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'completed_repackages_report' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица daily_summary последние обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'daily_summary'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "daily_summary дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'daily_summary' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица marginality_orders_by_act_date последние обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'marginality_orders_by_act_date'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "marginality_orders_by_act_date дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'marginality_orders_by_act_date' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица accounts последние обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'accounts'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "accounts дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'accounts' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица natural_indicators_by_contracts_segments последние обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'natural_indicators_by_contracts_segments'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "natural_indicators_by_contracts_segments дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'natural_indicators_by_contracts_segments' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица natural_indicators_by_transaction_fact_date обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'natural_indicators_by_transaction_fact_date'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "natural_indicators_by_transaction_fact_date дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'natural_indicators_by_transaction_fact_date' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица orders_marginality_report обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'orders_marginality_report'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "orders_marginality_report дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'orders_marginality_report' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица datacore_freight обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'datacore_freight'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "datacore_freight дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'datacore_freight' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица rzhd_by_operations_report обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'rzhd_by_operations_report'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "rzhd_by_operations_report дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'rzhd_by_operations_report' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица consignments обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'consignments'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "consignments дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'consignments' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица accounting_documents_requests обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'accounting_documents_requests'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "accounting_documents_requests дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'accounting_documents_requests' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица natural_indicators_of_railway_reception_and_dispatch обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'natural_indicators_of_railway_reception_and_dispatch'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "natural_indicators_of_railway_reception_and_dispatch дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'natural_indicators_of_railway_reception_and_dispatch' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица auto_pickup_general_report обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'auto_pickup_general_report'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "auto_pickup_general_report дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'auto_pickup_general_report' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица autovisits обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 70 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'autovisits'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "autovisits дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 70 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'autovisits' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица freight_rates обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 70 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'freight_rates'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "freight_rates дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 70 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'freight_rates' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица reference_counterparties обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 80 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'reference_counterparties'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "reference_counterparties дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 80 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'reference_counterparties' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица export_bookings обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 80 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'export_bookings'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "export_bookings дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 80 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'export_bookings' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица import_bookings обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 90 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'import_bookings'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "import_bookings дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 90 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'import_bookings' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица transport_units обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 90 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'transport_units'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "transport_units дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 90 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'transport_units' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица orders_report обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 100 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'orders_report'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "orders_report дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 100 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'orders_report' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица ruscon_products обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 100 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'ruscon_products'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "ruscon_products дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 100 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'ruscon_products' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица reference_locations обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 110 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'reference_locations'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "reference_locations дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 110 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'reference_locations' AND x.is_success = TRUE ;"
    }
   ]
  },
  {
   "title": "Таблица manager_evaluation обновления",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 110 },
   "targets": [
    {
     "rawSql": "SELECT max(date) as update_date,SUM(`count`) as key_id_count\r\nFROM (\r\n\t(SELECT   toDate(x.`datetime`) as `date`, COUNT(x.key_id)  as `count`\r\n\t\tFROM DataCore.rmq_log x\r\n\t\tWHERE x.`table` = 'manager_evaluation'  AND x.is_success = TRUE \r\n\t\tGROUP BY  x.key_id, x.`datetime`)\r\n\t) z_q  \r\nGROUP BY date \r\nORDER BY 1 DESC \r\nLIMIT 10"
    }
   ]
  },
  {
   "title": "manager_evaluation дата и время последнего обновления ",
   "type": "table",
   "description": "Дата и время последнего обновления",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 110 },
   "targets": [
    {
     "rawSql": "SELECT   max(toTimeZone(x.`datetime`,'Europe/Moscow')) as last_update_datetime\r\nFROM DataCore.rmq_log x\r\nWHERE x.`table` = 'manager_evaluation' AND x.is_success = TRUE ;"
    }
   ]
  }
 ]
}