{
 "title": "Report On Orders",
 "description": "Суммарное количество загруженных строк, отчет по поручениям",
 "tags": [
  "clickhouse",
  "db",
  "report_on_orders"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "NULL в export и auto_tracking_failed",
   "type": "stat",
   "description": "Кол-во строк",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS \"all_null\", (SELECT COUNT(*) FROM auto_tracking_failed atf WHERE direction ilike '%export%' AND terminal ilike '%нутэп%') AS \"auto_tracking_faild_null\"\r\nFROM export e2 WHERE tracking_seaport IS NULL"
    }
   ]
  },
  {
   "title": " Tracking seaport ilike '%novoros%'' кол-во строк",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT line,COUNT(*) AS \"count_row\"\r\nFROM export\r\nWHERE tracking_seaport ilike '%novoros%'\r\nGROUP BY line "
    }
   ]
  },
  {
   "title": "Кол-во строк, где line ilike \"%агентство%\"  OR line ilike \"%gstar%\"",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT line, COUNT(*) AS \"count_row\"\r\nFROM export\r\nWHERE terminal ilike '%нутэп%' AND (line ilike '%агентство%' OR line ilike '%gstar%')\r\nGROUP BY line"
    }
   ]
  },
  {
   "title": "Накопительное количество загруженных строк",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT toDateTime(query_start_time),SUM(SUM(written_rows)) OVER(partition by date_trunc('day',query_start_time) order by query_start_time ) as \"кол-во загруженных строк\"\r\nFROM system.query_log\r\nWHERE current_database ='default' and query_kind = 'Insert' and query ilike '%export %' and type = 'QueryFinish'\r\nGROUP BY query_start_time\r\nORDER BY query_start_time"
    }
   ]
  },
  {
   "title": "Среднее количество запросов в 1 минуту",
   "type": "timeseries",
   "description": "Эта метрика позволяет отследить количество POST-запросов на конкретный эндпоинт за минуту, помогая выявить активность пользователей и пики нагрузки на API.",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 5 },
   "targets": [
    {
     "expr": "increase(app_requests_total{method=\"POST\", endpoint=\"/\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "кол-во строк общее, только NULL, кол-во в auto_tracking_faild",
   "type": "table",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT t.line AS \"линия\",year_parsed_on AS \"год\",month_parsed_on AS \"месяц\",  all_count, null_count, auto_tracking_faild_count\r\nFROM (SELECT year_parsed_on ,month_parsed_on ,line, COUNT(*) AS \"all_count\", COUNT(line) FILTER (WHERE tracking_seaport IS NULL) AS \"null_count\"\r\nFROM export\r\nWHERE terminal ilike '%нутэп%'\r\nGROUP BY month_parsed_on , year_parsed_on ,line\r\n) AS t LEFT JOIN (SELECT `month` , `year` ,line, COUNT(*) AS \"auto_tracking_faild_count\"\r\nFROM auto_tracking_failed atf \r\nWHERE direction ilike '%export%' AND terminal ilike '%нутэп%'\r\nGROUP BY `month` , `year` ,line) AS t1 ON t.year_parsed_on = t1.`year` AND t.month_parsed_on = t1.`month` AND t.line=t1.line\r\nORDER BY year_parsed_on DESC , month_parsed_on DESC , t.line ASC"
    }
   ]
  },
  {
   "title": "Объем загруженных данных через insert ",
   "type": "state-timeline",
   "description": "для временного промежутка выбранного на дашборде",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT toDateTime(query_start_time),SUM(SUM(written_rows)) OVER(partition by date_trunc('day',query_start_time) order by query_start_time ) as \"кол-во загруженных строк\"\r\nFROM system.query_log\r\nWHERE current_database ='default' and query_kind = 'Insert' and query ilike '%export %' and type = 'QueryFinish'\r\nGROUP BY query_start_time\r\nORDER BY query_start_time"
    }
   ]
  }
 ]
}