{
 "title": "Rzhd Analysis",
 "tags": [
  "clickhouse",
  "db"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Схема",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT current_database, count(query_id) as cnt FROM \"system\".\"query_log\" WHERE ( query_duration_ms > 3000 ) AND ( http_user_agent = 'DataLens' ) AND ( type = 'QueryFinish' ) GROUP BY current_database ORDER BY cnt DESC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Таблица",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT table_name, count(query_id) AS cnt \nFROM (SELECT query_id, arrayJoin(tables) AS table_name \nFROM system.query_log \nWHERE query_duration_ms > 10000 \nAND http_user_agent = 'DataLens' \nAND type = 'QueryFinish' \nAND current_database = 'rzhd' \nAND event_date > now() - INTERVAL 7 DAY) \nGROUP BY table_name \nORDER BY cnt DESC \nLIMIT 1000;\n"
    }
   ]
  },
  {
   "title": "Столбцы",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n    substring(column_name, position(column_name, '.') + 1) AS clean_column_name,\n    count(query_id) AS cnt\nFROM\n(\n    SELECT\n        query_id,\n        arrayJoin(columns) AS column_string,\n        arrayJoin(extractAll(column_string, '\\\\b\\\\w+\\\\.\\\\w+\\\\b.\\\\w+\\\\b')) AS column_name\n    FROM system.query_log\n    WHERE\n        type = 'QueryFinish'\n        AND query_duration_ms > 10000\n        AND http_user_agent = 'DataLens'\n        AND current_database = 'rzhd'\n        AND event_date > now() - INTERVAL 7 DAY\n)\nGROUP BY clean_column_name\nORDER BY cnt DESC\nLIMIT 1000;"
    }
   ]
  },
  {
   "title": "Длительные запросы",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT query_id, query_duration_ms/1000 as seconds \nFROM \"system\".\"query_log\"\nWHERE ( query_duration_ms > 3000 ) \nAND ( http_user_agent LIKE '%DataLens%' ) \nAND ( databases = ['rzhd'] ) \nAND ( type = 'QueryFinish' ) \nAND ( type = 'QueryFinish' )\nAND (event_date > now() - INTERVAL 7 DAY)\n ORDER BY query_duration_ms DESC LIMIT 100"
    }
   ]
  },
  {
   "title": "Используемая память",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT query_id, memory_usage/1000000 as megabytes \nFROM \"system\".\"query_log\" \nWHERE ( http_user_agent = 'DataLens' ) \nAND ( type = 'QueryFinish' ) \nAND ( query_duration_ms > 35000 )\nAND (event_date > now() - INTERVAL 7 DAY)\nORDER BY memory_usage DESC LIMIT 100"
    }
   ]
  },
  {
   "title": "Количество прочитанных строк",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT read_rows/1000000 as million, query_id \nFROM \"system\".\"query_log\" \nWHERE ( query_duration_ms > 3000 ) \nAND ( type = 'QueryFinish' ) \nAND ( http_user_agent = 'DataLens' ) \nAND (event_date > now() - INTERVAL 1 DAY)\nORDER BY query_duration_ms DESC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Ошибки",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n    query_id,\n    exception_code,\n    exception\nFROM \"system\".\"query_log\"\nWHERE \n    http_user_agent LIKE '%DataLens%' \n    AND exception_code != 0\n    AND event_date > now() - INTERVAL 7 DAY\nORDER BY event_date DESC"
    }
   ]
  }
 ]
}